# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23385b01cab6d7e794c67e08044ab37594a3934210da74a89b62c0980ef61975d362632c08fb9d58ac5c329c248d3a4a8f70514cf724951f7add8f05ba03b787

test:
  secret_key_base: 694335ac1d3882799bbda58769adfff45b883f5a53d5abac0c19ee16862c5d4abd604ac4429216d5edba5dd41062aa7c556c4afea65e294e7035ed3c57d14d0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
